import jsPDF from 'jspdf';
import 'jspdf-autotable';

const formatDate = (date) => {
  if (!date) return 'N/A';
  const d = new Date(date);
  return isNaN(d.getTime()) ? 'N/A' : d.toLocaleDateString();
};

const formatCurrency = (amount) => {
  if (amount === undefined || amount === null) return 'NPR 0';
  return 'NPR ' + Number(amount).toLocaleString();
};

export const generateApplicationPDF = (application) => {
  if (!application) return;

  const doc = new jsPDF();
  
  // Add Header
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235); // Blue
  doc.text('Home Buyer Portal - Nepal', 105, 20, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setTextColor(100);
  doc.text(`Application Report: #${application.applicationId}`, 105, 30, { align: 'center' });

  // Add Metadata
  doc.setFontSize(10);
  doc.text(`Status: ${(application.status || 'pending').toUpperCase()}`, 14, 45);
  doc.text(`Submitted On: ${formatDate(application.submittedAt)}`, 140, 45);

  let startY = 55;

  // Personal Info Table
  doc.autoTable({
    startY: startY,
    head: [['Personal Information', '']],
    body: [
      ['Full Name', application.personalInfo?.fullName || 'N/A'],
      ['Citizenship Number', application.personalInfo?.citizenshipNumber || 'N/A'],
      ['Email', application.personalInfo?.email || 'N/A'],
      ['Phone', application.personalInfo?.phone || 'N/A']
    ],
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235] }
  });
  
  startY = doc.lastAutoTable.finalY + 10;

  // Employment & Property Table
  doc.autoTable({
    startY: startY,
    head: [['Employment & Property', 'Details']],
    body: [
      ['Employment Type', application.employment?.type || 'N/A'],
      ['Monthly Income', formatCurrency(application.employment?.monthlyIncome)],
      ['Employer Name', application.employment?.employerName || 'N/A'],
      ['Location', `${application.property?.district || 'N/A'}, ${application.property?.municipality || 'N/A'}`],
      ['Property Type', application.property?.type || 'N/A'],
      ['Property Cost', formatCurrency(application.property?.cost)]
    ],
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129] } // Emerald
  });

  startY = doc.lastAutoTable.finalY + 10;

  // Subsidy & Selected Bank Table
  const finalTableBody = [
    ['Subsidy Requested', formatCurrency(application.subsidyRequested)],
    ['Subsidy Approved', application.subsidyApproved > 0 ? formatCurrency(application.subsidyApproved) : 'Pending/None']
  ];

  if (application.rejectionReason) {
    finalTableBody.push(['Rejection Reason', application.rejectionReason]);
  }

  if (application.officerNotes) {
    finalTableBody.push(['Officer Notes', application.officerNotes]);
  }

  const selectedOffer = application.bankOffers?.find(o => o.status === 'accepted');
  if (selectedOffer) {
    finalTableBody.push(['Selected Bank', selectedOffer.bankName]);
    finalTableBody.push(['Loan Amount', formatCurrency(selectedOffer.loanAmount)]);
    finalTableBody.push(['Interest Rate', `${selectedOffer.interestRate}%`]);
    finalTableBody.push(['EMI', formatCurrency(selectedOffer.emi)]);
  }

  doc.autoTable({
    startY: startY,
    head: [['Final Subsidy & Loan Summary', '']],
    body: finalTableBody,
    theme: 'grid',
    headStyles: { fillColor: [139, 92, 246] } // Violet
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Home Buyer Portal on ${new Date().toLocaleString()}`, 14, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
  }

  // Save the PDF
  doc.save(`Application_${application.applicationId}.pdf`);
};
